<?php

include 'product-object.php';
include 'product-image-object.php';
include 'product-image-layout-enum.php';

$GLOBALS['data'] = array(
    "brainston" => new Product("BRAINSTON",
        "Logo & UI/UX App",
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        "img/brainston/brainston.jpg",
        "#FD3C1DA6",
        array(
            new ProductImage("img/brainston/Brainston-01.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/brainston/Brainston-02.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/brainston/Brainston-03.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/brainston/Brainston-04.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/brainston/Brainston-05.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/brainston/Brainston-06.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/brainston/Brainston-07.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/brainston/Brainston-08.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/brainston/Brainston-09.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/brainston/Brainston-10.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/brainston/Brainston-11.jpg",
                ProductImageLayout::FULLSCREEN),
        )
    ),
    "kauha" => new Product("KAUHA",
        "Chocolate Label",
        "DESCRIPTION",
        "img/kauha/kauha.jpg",
        "#6F020FA6",
        array(
            new ProductImage("img/kauha/kauha-01.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/kauha/kauha-02.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/kauha/kauha-03.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/kauha/kauha-04.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/kauha/kauha-05.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/kauha/kauha-06.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/kauha/kauha-07.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/kauha/kauha-08.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/kauha/kauha-09.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/kauha/kauha-10.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/kauha/kauha-11.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/kauha/kauha-12.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/kauha/kauha-13.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/kauha/kauha-14.jpg",
                ProductImageLayout::FULLSCREEN),
        )
    ),
    "various" => new Product("VARIOUS",
        "Post Design Social Media",
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        "img/various-social/various-social.jpg",
        "#933B98A6",
        array(
            new ProductImage("img/various-social/various-social.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/various-social/social-01.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/various-social/social-02.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/various-social/social-03.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/various-social/social-04.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/various-social/social-05.jpg",
                ProductImageLayout::FULLSCREEN),
        )
    ),
    "aside" => new Product("ASIDE",
        "Magazine Design",
        "DESCRIPTION",
        "img/aside/aside.jpg",
        "#FCBA20A6",
        array(
            new ProductImage("img/aside/aside-01.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/aside/aside-02.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/aside/aside-03.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/aside/aside-04.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/aside/aside-05.jpg",
                ProductImageLayout::FULLSCREEN),
        )
    ),
    "heidrunn" => new Product("HEIDRUNN",
        "Beer Label Design",
        "DESCRIPTION",
        "img/heidrunn/heidrunn.jpg",
        "#043673A6",
        array(
            new ProductImage("img/heidrunn/heidrunn-01.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/heidrunn/heidrunn-02.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/heidrunn/heidrunn-03.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/heidrunn/heidrunn-04.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/heidrunn/heidrunn-05.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/heidrunn/heidrunn-06.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/heidrunn/heidrunn-07.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/heidrunn/heidrunn-08.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/heidrunn/heidrunn-09.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/heidrunn/heidrunn-10.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/heidrunn/heidrunn-11.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/heidrunn/heidrunn-12.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/heidrunn/heidrunn-13.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/heidrunn/heidrunn-14.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/heidrunn/heidrunn-15.jpg",
                ProductImageLayout::FULLSCREEN),
        )
    ),
    "revoison" => new Product("RÉVOISON",
        "Logo Design & Branding",
        "DESCRIPTION",
        "img/revoison/revoison.jpg",
        "#1E2426A6",
        array(
            new ProductImage("img/revoison/revoison-01.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/revoison/revoison-02.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/revoison/revoison-03.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/revoison/revoison-04.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/revoison/revoison-05.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/revoison/revoison-06.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/revoison/revoison-07.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/revoison/revoison-08.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/revoison/revoison-09.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/revoison/revoison-10.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/revoison/revoison-11.jpg",
                ProductImageLayout::FULLSCREEN),
        )
    ),
);
