<?php

include 'product-object.php';
include 'product-image-object.php';
include 'product-image-layout-enum.php';

$GLOBALS['data'] = array(
    "brainston" => new Product("BRAINSTON",
        "Logo Design & UI/UX App",
        "Creazione di un marchio e relativa UI/UX design per piattaforma di crowdfunding utilizzando la tecnica “scale-up”, iniziando dunque dalla progettazione della versione mobile. Questo marchio si occuperà di crowdfunding solo in ambito design, abbracciando in ogni caso diversi settori. Il concept del logo nasce dall’esigenza di riconoscere nel mercato la propria presenza visiva con un marchio semplice e preciso.",
        "img/brainston/brainston.jpg",
        "#FD3C1DA6",
        array(
            new ProductImage("img/brainston/Brainston-01.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/brainston/Brainston-02.jpg",
                ProductImageLayout::RIGHT_DESCRIPTION,
                       [],
            "Il naming in questione “Brainston” proviene dall’insieme di due parole inglesi, rispettivamente brainstorm (idea geniale); riferito ai futuri utenti che avranno brillanti idee da voler realizzare proponendole sul sito in cerca di finanziatori, e on, per dare un’idea di “acceso” come simbolo per mettere in funzione la propria creatività. A sinistra troviamo il pittogramma che rapprensenta il cervello a forma della lettera B: ossia la prima lettera del naming. Subito dopo logotipo e payoff; quest’ultimo con testo “express your creativity” (in italiano “esprimi la tua creatività”) invita ed esorta a tutti coloro che hanno un progetto da voler realizzare a metterla in pratica, avendo l’opportunità di trovare collaboratori interessati ad investire, tramutando il proprio sogno in realtà."),
            new ProductImage("img/brainston/Brainston-03.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/brainston/Brainston-04.jpg",
                ProductImageLayout::RIGHT_DESCRIPTION,
                [],
            "L’area di rispetto indica lo spazio minimo essenziale tra il logo ed altri elementi.\nL’area in questione equivale esattamente a 1/3x."),
            new ProductImage("img/brainston/Brainston-05.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/brainston/Brainston-06.jpg",
                ProductImageLayout::RIGHT_DESCRIPTION,
            [],
            "Il logo mantiene un’ottima leggibilità in tutte le dimensioni, ma è consigliabile la non riduzione al di sotto dei 5 cm in altezza."),
            new ProductImage("img/brainston/Brainston-07.jpg",
                ProductImageLayout::BOTTOM_DESCRIPTION,
            [],
            "Le seguenti icone sopra rappresentate sono state utilzzate per lo sviluppo del sito web."),
            new ProductImage("img/brainston/Brainston-08.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/brainston/Brainston-09.jpg",
                ProductImageLayout::BOTTOM_DESCRIPTION,
            [],
            "Flowchart has been realized through the use of <a href=\"https://www.miro.com\" target=\"_blank\">www.miro.com</a>"),
            new ProductImage("img/brainston/Brainston-10.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/brainston/Brainston-11.jpg",
                ProductImageLayout::FULLSCREEN),
        )
    ),
    "kauha" => new Product("KAUHA",
        "Chocolate Label",
        "DESCRIPTION",
        "img/kauha/kauha.jpg",
        "#6F020FA6",
        array(
            new ProductImage("img/kauha/kauha-01.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/kauha/kauha-02.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/kauha/kauha-03.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/kauha/kauha-04.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/kauha/kauha-05.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/kauha/kauha-06.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/kauha/kauha-07.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/kauha/kauha-08.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/kauha/kauha-09.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/kauha/kauha-10.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/kauha/kauha-11.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/kauha/kauha-12.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/kauha/kauha-13.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/kauha/kauha-14.jpg",
                ProductImageLayout::FULLSCREEN),
        )
    ),
    "various" => new Product("VARIOUS",
        "Post Design Social Media",
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        "img/various-social/various-social.jpg",
        "#933B98A6",
        array(
            new ProductImage("img/various-social/various-social.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/various-social/social-01.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/various-social/social-02.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/various-social/social-03.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/various-social/social-04.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/various-social/social-05.jpg",
                ProductImageLayout::FULLSCREEN),
        )
    ),
    "aside" => new Product("ASIDE",
        "Magazine Design",
        "DESCRIPTION",
        "img/aside/aside.jpg",
        "#FCBA20A6",
        array(
            new ProductImage("img/aside/aside-01.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/aside/aside-02.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/aside/aside-03.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/aside/aside-04.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/aside/aside-05.jpg",
                ProductImageLayout::FULLSCREEN),
        )
    ),
    "heidrunn" => new Product("HEIDRUNN",
        "Beer Label Design",
        "DESCRIPTION",
        "img/heidrunn/heidrunn.jpg",
        "#043673A6",
        array(
            new ProductImage("img/heidrunn/heidrunn-01.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/heidrunn/heidrunn-02.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/heidrunn/heidrunn-03.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/heidrunn/heidrunn-04.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/heidrunn/heidrunn-05.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/heidrunn/heidrunn-06.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/heidrunn/heidrunn-07.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/heidrunn/heidrunn-08.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/heidrunn/heidrunn-09.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/heidrunn/heidrunn-10.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/heidrunn/heidrunn-11.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/heidrunn/heidrunn-12.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/heidrunn/heidrunn-13.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/heidrunn/heidrunn-14.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/heidrunn/heidrunn-15.jpg",
                ProductImageLayout::FULLSCREEN),
        )
    ),
    "revoison" => new Product("RÉVOISON",
        "Logo Design & Branding",
        "DESCRIPTION",
        "img/revoison/revoison.jpg",
        "#1E2426A6",
        array(
            new ProductImage("img/revoison/revoison-01.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/revoison/revoison-02.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/revoison/revoison-03.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/revoison/revoison-04.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/revoison/revoison-05.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/revoison/revoison-06.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/revoison/revoison-07.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/revoison/revoison-08.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/revoison/revoison-09.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/revoison/revoison-10.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/revoison/revoison-11.jpg",
                ProductImageLayout::FULLSCREEN),
        )
    ),
);
