<?php

include 'product-object.php';
include 'product-image-object.php';
include 'product-image-layout-enum.php';

$GLOBALS['data'] = array(
    "brainston" => new Product("BRAINSTON",
        "Logo Design & UI/UX App",
        "Creation of a brand and related UI/UX design for crowdfunding platform using the “scale-up” technique, starting therefore from the design of the mobile version. This brand will only deal with crowdfunding in the design field, in any case embracing different sectors. The concept of the logo was born from the need to recognize one's visual presence in the market with a simple and precise brand.",
        "img/brainston/brainston.jpg",
        "#FD3C1DA6",
        array(
            new ProductImage("img/brainston/Brainston-01.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/brainston/Brainston-02.jpg",
                ProductImageLayout::RIGHT_DESCRIPTION,
                       [],
            "The naming \"Brainston\" comes from the set of two English words, respectively <b>brainstorm</b>, referring to future users who will have brilliant ideas to realize by proposing them on the site in search of financiers, and <b>on</b>, to give an idea of \"lit\" as a symbol for put your creativity to work. On the left we find the pictogram representing the brain in the shape of the letter B: that is, the first letter of the naming. Immediately after the logo and payoff; the latter with the text \"express your creativity\" invites all those who have a project they want to carry out to put it into practice, having the opportunity to find collaborators interested in investing, turning their dream into reality."),
            new ProductImage("img/brainston/Brainston-03.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/brainston/Brainston-04.jpg",
                ProductImageLayout::RIGHT_DESCRIPTION,
                [],
            "The buffer area indicates the minimum essential space between the logo and other elements. \nThe area in question is exactly equivalent to 1/3x."),
            new ProductImage("img/brainston/Brainston-05.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/brainston/Brainston-06.jpg",
                ProductImageLayout::RIGHT_DESCRIPTION,
            [],
            "The logo maintains excellent readability in all dimensions, but it is advisable not to reduce it below 5 cm in height."),
            new ProductImage("img/brainston/Brainston-07.jpg",
                ProductImageLayout::BOTTOM_DESCRIPTION,
            [],
            "The following icons represented above were used for the development of the website."),
            new ProductImage("img/brainston/Brainston-08.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/brainston/Brainston-09.jpg",
                ProductImageLayout::BOTTOM_DESCRIPTION,
            [],
            "Flowchart has been realized through the use of <a href=\"https://www.miro.com\" target=\"_blank\">www.miro.com</a>"),
            new ProductImage("img/brainston/Brainston-10.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/brainston/Brainston-11.jpg",
                ProductImageLayout::FULLSCREEN),
        )
    ),
    "kauha" => new Product("KAUHA",
        "Chocolate Label",
        "DESCRIPTION",
        "img/kauha/kauha.jpg",
        "#6F020FA6",
        array(
            new ProductImage("img/kauha/kauha-01.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/kauha/kauha-02.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/kauha/kauha-03.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/kauha/kauha-04.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/kauha/kauha-05.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/kauha/kauha-06.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/kauha/kauha-07.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/kauha/kauha-08.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/kauha/kauha-09.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/kauha/kauha-10.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/kauha/kauha-11.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/kauha/kauha-12.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/kauha/kauha-13.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/kauha/kauha-14.jpg",
                ProductImageLayout::FULLSCREEN),
        )
    ),
    "various" => new Product("VARIOUS",
        "Post Design Social Media",
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        "img/various-social/various-social.jpg",
        "#933B98A6",
        array(
            new ProductImage("img/various-social/various-social.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/various-social/social-01.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/various-social/social-02.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/various-social/social-03.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/various-social/social-04.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/various-social/social-05.jpg",
                ProductImageLayout::FULLSCREEN),
        )
    ),
    "aside" => new Product("ASIDE",
        "Magazine Design",
        "DESCRIPTION",
        "img/aside/aside.jpg",
        "#FCBA20A6",
        array(
            new ProductImage("img/aside/aside-01.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/aside/aside-02.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/aside/aside-03.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/aside/aside-04.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/aside/aside-05.jpg",
                ProductImageLayout::FULLSCREEN),
        )
    ),
    "heidrunn" => new Product("HEIDRUNN",
        "Beer Label Design",
        "DESCRIPTION",
        "img/heidrunn/heidrunn.jpg",
        "#043673A6",
        array(
            new ProductImage("img/heidrunn/heidrunn-01.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/heidrunn/heidrunn-02.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/heidrunn/heidrunn-03.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/heidrunn/heidrunn-04.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/heidrunn/heidrunn-05.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/heidrunn/heidrunn-06.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/heidrunn/heidrunn-07.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/heidrunn/heidrunn-08.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/heidrunn/heidrunn-09.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/heidrunn/heidrunn-10.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/heidrunn/heidrunn-11.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/heidrunn/heidrunn-12.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/heidrunn/heidrunn-13.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/heidrunn/heidrunn-14.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/heidrunn/heidrunn-15.jpg",
                ProductImageLayout::FULLSCREEN),
        )
    ),
    "revoison" => new Product("RÉVOISON",
        "Logo Design & Branding",
        "DESCRIPTION",
        "img/revoison/revoison.jpg",
        "#1E2426A6",
        array(
            new ProductImage("img/revoison/revoison-01.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/revoison/revoison-02.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/revoison/revoison-03.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/revoison/revoison-04.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/revoison/revoison-05.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/revoison/revoison-06.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/revoison/revoison-07.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/revoison/revoison-08.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/revoison/revoison-09.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/revoison/revoison-10.jpg",
                ProductImageLayout::FULLSCREEN),
            new ProductImage("img/revoison/revoison-11.jpg",
                ProductImageLayout::FULLSCREEN),
        )
    ),
);
